# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trustchain.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trustchain.proto',
  package='trustchain',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10trustchain.proto\x12\ntrustchain\"@\n\x0cTradeRequest\x12\x11\n\tpublicKey\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x03\x12\x0e\n\x06\x62locks\x18\x03 \x03(\x0c\"3\n\nTradeReply\x12\x15\n\rproposedBlock\x18\x01 \x01(\x0c\x12\x0e\n\x06\x62locks\x18\x02 \x03(\x0c\"`\n\x10SignatureRequest\x12\x13\n\x0btransaction\x18\x01 \x01(\x0c\x12!\n\x06\x63hains\x18\x02 \x03(\x0b\x32\x11.trustchain.Chain\x12\x14\n\x0cwitnessCount\x18\x03 \x01(\x03\"\x17\n\x05\x43hain\x12\x0e\n\x06\x62locks\x18\x01 \x03(\x0c\"Y\n\x05\x42lock\x12\x13\n\x0btransaction\x18\x01 \x01(\x0c\x12\x12\n\nsignatures\x18\x02 \x03(\x0c\x12\'\n\twitnesses\x18\x03 \x03(\x0b\x32\x14.trustchain.Approval\"w\n\x0bTransaction\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x03\x12\n\n\x02ID\x18\x03 \x03(\x0c\x12\x14\n\x0cpreviousHash\x18\x04 \x03(\x0c\x12\x13\n\x0bsequence_no\x18\x05 \x03(\x04\x12\x0f\n\x07\x62\x61lance\x18\x06 \x03(\x03\"4\n\x08\x41pproval\x12\n\n\x02ID\x18\x01 \x01(\x0c\x12\t\n\x01i\x18\x02 \x01(\x04\x12\x11\n\tsignature\x18\x03 \x01(\x0c\"+\n\x08Nodelist\x12\x1f\n\x05nodes\x18\x01 \x03(\x0b\x32\x10.trustchain.Node\"B\n\x04Node\x12\x14\n\x0c\x66riendlyName\x18\x01 \x01(\t\x12\n\n\x02ID\x18\x02 \x01(\x0c\x12\n\n\x02IP\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x04\x62\x06proto3')
)




_TRADEREQUEST = _descriptor.Descriptor(
  name='TradeRequest',
  full_name='trustchain.TradeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='publicKey', full_name='trustchain.TradeRequest.publicKey', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='trustchain.TradeRequest.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blocks', full_name='trustchain.TradeRequest.blocks', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=96,
)


_TRADEREPLY = _descriptor.Descriptor(
  name='TradeReply',
  full_name='trustchain.TradeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposedBlock', full_name='trustchain.TradeReply.proposedBlock', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blocks', full_name='trustchain.TradeReply.blocks', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=149,
)


_SIGNATUREREQUEST = _descriptor.Descriptor(
  name='SignatureRequest',
  full_name='trustchain.SignatureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction', full_name='trustchain.SignatureRequest.transaction', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chains', full_name='trustchain.SignatureRequest.chains', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='witnessCount', full_name='trustchain.SignatureRequest.witnessCount', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=247,
)


_CHAIN = _descriptor.Descriptor(
  name='Chain',
  full_name='trustchain.Chain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blocks', full_name='trustchain.Chain.blocks', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=272,
)


_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='trustchain.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction', full_name='trustchain.Block.transaction', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signatures', full_name='trustchain.Block.signatures', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='witnesses', full_name='trustchain.Block.witnesses', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=363,
)


_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='trustchain.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='trustchain.Transaction.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='trustchain.Transaction.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ID', full_name='trustchain.Transaction.ID', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='previousHash', full_name='trustchain.Transaction.previousHash', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence_no', full_name='trustchain.Transaction.sequence_no', index=4,
      number=5, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='trustchain.Transaction.balance', index=5,
      number=6, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=484,
)


_APPROVAL = _descriptor.Descriptor(
  name='Approval',
  full_name='trustchain.Approval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='trustchain.Approval.ID', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='i', full_name='trustchain.Approval.i', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='trustchain.Approval.signature', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=486,
  serialized_end=538,
)


_NODELIST = _descriptor.Descriptor(
  name='Nodelist',
  full_name='trustchain.Nodelist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='trustchain.Nodelist.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=583,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='trustchain.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='friendlyName', full_name='trustchain.Node.friendlyName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ID', full_name='trustchain.Node.ID', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IP', full_name='trustchain.Node.IP', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='trustchain.Node.port', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=651,
)

_SIGNATUREREQUEST.fields_by_name['chains'].message_type = _CHAIN
_BLOCK.fields_by_name['witnesses'].message_type = _APPROVAL
_NODELIST.fields_by_name['nodes'].message_type = _NODE
DESCRIPTOR.message_types_by_name['TradeRequest'] = _TRADEREQUEST
DESCRIPTOR.message_types_by_name['TradeReply'] = _TRADEREPLY
DESCRIPTOR.message_types_by_name['SignatureRequest'] = _SIGNATUREREQUEST
DESCRIPTOR.message_types_by_name['Chain'] = _CHAIN
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
DESCRIPTOR.message_types_by_name['Approval'] = _APPROVAL
DESCRIPTOR.message_types_by_name['Nodelist'] = _NODELIST
DESCRIPTOR.message_types_by_name['Node'] = _NODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TradeRequest = _reflection.GeneratedProtocolMessageType('TradeRequest', (_message.Message,), dict(
  DESCRIPTOR = _TRADEREQUEST,
  __module__ = 'trustchain_pb2'
  # @@protoc_insertion_point(class_scope:trustchain.TradeRequest)
  ))
_sym_db.RegisterMessage(TradeRequest)

TradeReply = _reflection.GeneratedProtocolMessageType('TradeReply', (_message.Message,), dict(
  DESCRIPTOR = _TRADEREPLY,
  __module__ = 'trustchain_pb2'
  # @@protoc_insertion_point(class_scope:trustchain.TradeReply)
  ))
_sym_db.RegisterMessage(TradeReply)

SignatureRequest = _reflection.GeneratedProtocolMessageType('SignatureRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIGNATUREREQUEST,
  __module__ = 'trustchain_pb2'
  # @@protoc_insertion_point(class_scope:trustchain.SignatureRequest)
  ))
_sym_db.RegisterMessage(SignatureRequest)

Chain = _reflection.GeneratedProtocolMessageType('Chain', (_message.Message,), dict(
  DESCRIPTOR = _CHAIN,
  __module__ = 'trustchain_pb2'
  # @@protoc_insertion_point(class_scope:trustchain.Chain)
  ))
_sym_db.RegisterMessage(Chain)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
  DESCRIPTOR = _BLOCK,
  __module__ = 'trustchain_pb2'
  # @@protoc_insertion_point(class_scope:trustchain.Block)
  ))
_sym_db.RegisterMessage(Block)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTION,
  __module__ = 'trustchain_pb2'
  # @@protoc_insertion_point(class_scope:trustchain.Transaction)
  ))
_sym_db.RegisterMessage(Transaction)

Approval = _reflection.GeneratedProtocolMessageType('Approval', (_message.Message,), dict(
  DESCRIPTOR = _APPROVAL,
  __module__ = 'trustchain_pb2'
  # @@protoc_insertion_point(class_scope:trustchain.Approval)
  ))
_sym_db.RegisterMessage(Approval)

Nodelist = _reflection.GeneratedProtocolMessageType('Nodelist', (_message.Message,), dict(
  DESCRIPTOR = _NODELIST,
  __module__ = 'trustchain_pb2'
  # @@protoc_insertion_point(class_scope:trustchain.Nodelist)
  ))
_sym_db.RegisterMessage(Nodelist)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
  DESCRIPTOR = _NODE,
  __module__ = 'trustchain_pb2'
  # @@protoc_insertion_point(class_scope:trustchain.Node)
  ))
_sym_db.RegisterMessage(Node)


# @@protoc_insertion_point(module_scope)
